version: 2
jobs:
  build:

    working_directory: ~/repo

    machine: true

    steps:
        - checkout

        - run:
            name: Install Dependencies
            command: |
              sudo apt-get install build-essential python-dev curl file git python-setuptools ruby

        - run:
            name: Intall Linuxbrew
            command: |
              ./install_brew.sh
              export PATH="$HOME/.linuxbrew/bin:$PATH"
              brew test easel.rb




