version: 2
jobs:
  build:

    working_directory: ~/repo

    machine: true

    steps:
        - checkout

        - run:
            name: Install Dependencies
            command: |
              sudo apt-get install build-essential python-dev curl file git python-setuptools ruby

        - run:
            name: Intall Linuxbrew
            command: |
              yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" || true

        - run:
            name: And Linuxbrew to PATH and Test
            command: |
              test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$PATH"
              test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
              test -r ~/.bash_profile && echo 'export PATH="$(brew --prefix)/bin:$PATH"' >>~/.bash_profile
              echo 'export PATH="$(brew --prefix)/bin:$PATH"' >>~/.profile
              brew install ./easel.rb
              brew test ./easel.rb



