version: 2
jobs:
  build:

    working_directory: ~/repo

    machine: true

    steps:
        - checkout

        - run:
            name: Install Dependencies
            command: |
              sudo apt-get install build-essential python-dev curl file git python-setuptools ruby

        - run:
            name: Intall Linuxbrew
            command: |
              yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" || true

        - run:
            name: Add Linuxbrew To Path
            command: |
              test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$PATH"
              test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
              test -r ~/.bash_profile && echo 'export PATH="$(brew --prefix)/bin:$PATH"' >>~/.bash_profile
              echo 'export PATH="$(brew --prefix)/bin:$PATH"' >>~/.profile

        - run:
            name: End-to-end Testing
            command: |
              ls -l
              brew test easel.rb



