version: 2
jobs:
  build:

    working_directory: ~/repo

    machine: true

    steps:
        - checkout

          # Install Linuxbrew Dependencies Via Apt
        - run:
            name: Install Dependencies
            command: |
              sudo apt-get install build-essential python-dev curl file git python-setuptools ruby

          # Install Linuxbrew (Note: Adding linuxbrew to the PATH here won't work since this run command is running
          # in its own shell. The parent shell (the one that calls the run command) is not effected.). Add yes | to
          # continue installing. Add || true to override linuxbrew install returning exit code 141. There may be a bug
          # when you install linuxbrew via a password where it returns 141 on a warning rather than error.
        - run:
            name: Intall Linuxbrew
            command: |
              yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" || true

          # Install Custom Linuxbrew Formulae (Note: Since the parent shell can't be given the path to linux brew we have to
          # add it to the path with in the run command (child shell).)
        - run:
            name: Install Custom Formulae
            command: |
              export PATH="$HOME/.linuxbrew/bin:$PATH"
              brew install ./easel.rb

              
          # Run Linuxbrew Tests (See note atop above run command.)
        - run:
            name: Test Custom Formulae
            command: |
              export PATH="$HOME/.linuxbrew/bin:$PATH"
              brew test ./easel.rb
              